### ISSUE TITLE
Bad file descriptor error when running in virtual terminal

### ISSUE THREAD

**Issue by nolash** [urwid/urwid#256]
I came across this error using [khal v0.9.6](https://github.com/pimutils/khal);

Running the `urwid` (1.3.1) examples works fine in xterm. But when I try to run in virtual terminal, it fails:

```
Traceback (most recent call last):
  File "bigtext.py", line 161, in <module>
    main()
  File "bigtext.py", line 158, in main
    BigTextDisplay().main()
  File "bigtext.py", line 142, in main
    self.loop.run()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/lash/data/src/virtualenv/urwid/lib/python3.6/site-packages/urwid/main_loop.py", line 703, in _loop
    ready, w, err = select.select(fds, [], fds, timeout)
OSError: [Errno 9] Bad file descriptor
```

Using Linux `4.11.3-1-ARCH` + `python 3.6.1`

**Comment by wardi** [comment]
This may have been fixed on master, just need to put out a release

**Comment by Drakota** [comment]
Any update on this? I'm getting the same issue here. Just found urwid tried doing the simple examples in the tutorial and it doesn't work.

**Comment by and3rson** [comment]
@Drakota @nolash Can you confirm that this currently still reproduces in master branch? I'm also on Arch 4.14.11-1 & Python 3.6.3 and the examples work for me.

**Comment by nolash** [comment]
@and3rson this is so long ago I can't remember anymore what it was I did.

Anyway I downloaded the repo and according to the readme installed and ran `tox` (which I'm pretty sure I didn't last time) in virtualenv. All tests passed.

If you let me know what still fails in your end, I can try to run the same thing as you to see.

**Comment by and3rson** [comment]
@nolash did the bigtext example work in a virtual terminal for you as well?

**Comment by nolash** [comment]
It runs on both `tty` and `pts` :)

**Comment by nolash** [comment]
Meanwhile I'm running `python 3.6.4` (`virtualenv 15.1.10`) and `4.14.13-1-ARCH`

**Comment by and3rson** [comment]
Thanks! I'm closing this issue.
