### ISSUE TITLE
Problems with positions method in urwid.ListWalker

### ISSUE THREAD

**Issue by kajojify** [urwid/urwid#294]
##### Description:
Hi! I am one of the [mitmproxy](https://github.com/mitmproxy/mitmproxy) contributors. We faced a problem. Some parts of our UI are based on `urwid.ListWalker`. For example, we have [FlowList](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/flowlist.py#L37), which looks:

![image](https://user-images.githubusercontent.com/20267977/37608075-3aade2a0-2ba2-11e8-8248-d315747d7bfb.png)

During the navigating everything works pretty good, except `home`/`end` buttons. If I press `home`/`end` button to reach the first/last item of a list, when interacting with `urwid.ListWalker`-based widget, mitmproxy is crashed with traceback:
```
Traceback (most recent call last):
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/master.py", line 227, in run
    self.loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/window.py", line 309, in keypress
    k = super().keypress(size, k)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/window.py", line 44, in keypress
    ret = super().keypress(size, key)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/kajoj/Mitmproxy/mitmproxy/mitmproxy/tools/console/flowlist.py", line 87, in keypress
    return urwid.ListBox.keypress(self, size, key)
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 1025, in keypress
    return actual_key(self._keypress_max_right())
  File "/home/kajoj/Mitmproxy/mitmproxy/venv/lib/python3.5/site-packages/urwid/listbox.py", line 1035, in _keypress_max_right
    self.focus_position = next(iter(self.body.positions(reverse=True)))
AttributeError: 'FlowListWalker' object has no attribute 'positions'
```

There is no any problem to add `positions` method inside each `urwid.ListWalker`-based class, but it will look pretty repetetive, since we have 6 `urwid.ListWalker`-based classes.
Moreover urwid documentation says `positions` method is optional - http://urwid.org/reference/list_walkers.html#urwid.SimpleListWalker.positions

So, could you please answer how it is supposed to behave? 
Is there any way to deal with `home`/`end` buttons without adding `positions` method everywhere?

Thank you for your attention!
All the best!

**Comment by rndusr** [comment]
SimpleListwalker comes with the positions() method implemented. Why don't you
use that instead of ListWalker?

You could also have a mixin class that provdes positions() and let the other
classes inherit from that.

**Comment by wardi** [comment]
SimpleListWalker is based on an actual list. ListWalker is just the protocol that a ListBox requires to function. Adding home+end that depends on the positions() method broke that protocol and should be fixed by urwid gracefully handling list walkers that don't have a positions() method.

**Comment by jvantuyl** [comment]
Can confirm that this is a problem with TreeWalker as well.

**Comment by xnox** [comment]
urwid/examples/treesample.py crashes.

**Comment by ulidtko** [comment]
This has been fixed just recently by #347.

**Comment by neumond** [comment]
Issue is still not fixed. ListBox with primitive ListWalker crashes on home/end.
